version: '3.8'

services:
  frontend:
    image: training:frontend-0.1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${UID:?err}
        - GID=${GID:?err}
    ports:
      - "${FRONT_PORT:-3000}:${FRONT_PORT:-3000}"
      - "${FRONT_PORT_HMR:-3010}:${FRONT_PORT_HMR:-3010}"
    command: >
      sh -c "yarn dev"
    working_dir: /app/src/
    volumes:
      - .:/app/src/
    env_file:
      - ./.env
volumes:
  yarn:
